version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sistema_de_monitoria_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sistema_de_monitoria
      MYSQL_USER: monitoria_user
      MYSQL_PASSWORD: monitoria_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitoria-network

volumes:
  mysql_data:

networks:
  monitoria-network:
