spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3305/sistema_de_monitoria?useUnicode=true&characterEncoding=UTF-8
    username: monitoria_user
    password: monitoria_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      # ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        useUnicode: true
        characterEncoding: utf8
        characterSetResults: utf8mb4

  sql:
    init:
      # mode: always
      mode: never

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"